"""initial migration

Revision ID: 232c263461d2
Revises:
Create Date: 2026-05-03 12:55:00.102075

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "232c263461d2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_identifier", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_files")),
    )
    op.create_index(
        op.f("ix_organization_files_file_name"),
        "organization_files",
        ["file_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_files_unique_identifier"),
        "organization_files",
        ["unique_identifier"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_organization_files_unique_identifier"), table_name="organization_files"
    )
    op.drop_index(
        op.f("ix_organization_files_file_name"), table_name="organization_files"
    )
    op.drop_table("organization_files")
    # ### end Alembic commands ###
