"""Add first migration

Revision ID: ccc1bffd03f9
Revises:
Create Date: 2026-05-04 15:17:25.324650

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ccc1bffd03f9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE documentstatusenum AS ENUM (
                'QUEUED_FOR_UPLOAD', 'UPLOADING', 'UPLOADED', 'UPLOAD_FAILED',
                'INDEXING', 'INDEXED', 'INDEXING_FAILED', 'FAILED'
            );
        EXCEPTION
            WHEN duplicate_object THEN NULL;
        END $$;
    """)

    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_identifier", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("file_size", sa.Float(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "QUEUED_FOR_UPLOAD",
                "UPLOADING",
                "UPLOADED",
                "UPLOAD_FAILED",
                "INDEXING",
                "INDEXED",
                "INDEXING_FAILED",
                "FAILED",
                name="documentstatusenum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(
        op.f("ix_documents_file_name"), "documents", ["file_name"], unique=False
    )
    op.create_index(
        op.f("ix_documents_unique_identifier"),
        "documents",
        ["unique_identifier"],
        unique=True,
    )
    op.create_table(
        "document_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column(
            "content_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("embedding", Vector(768), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_embeddings_document_id_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_embeddings")),
        sa.UniqueConstraint(
            "document_id",
            "page_number",
            name="uq_document_embeddings_document_id_page_number",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_embeddings")
    op.drop_index(op.f("ix_documents_unique_identifier"), table_name="documents")
    op.drop_index(op.f("ix_documents_file_name"), table_name="documents")
    op.drop_table("documents")
    sa.Enum(name="documentstatusenum").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
